### ISSUE TITLE
Octave convention difference

### ISSUE THREAD

**Issue by papitosan** [keijiro/MidiAnimationTrack#6]
First, thank you very much for sharing your work.
Everything run smoothly.

 I just noticed that there is on octave difference between the midi reciever and my imported midi track. 
Don't know if the problem come from the midi parsing or the reciever itself.
It's not actually a problem for me  but just wanted wanted you to know.

Thanks again!

**Comment by keijiro** [comment]
Thanks for pointing it out.

That's because there are differences between the scientific pitch notation (MIDI) and octave conventions in some DAWs.

https://en.wikipedia.org/wiki/Scientific_pitch_notation#Similar_systems

There is no best solution for this problem. At the moment, I think the current implementation makes sense because this package is "MIDI Animation Track" -- It should be based on the MIDI specifications.
